  version: "3"

  services:
    db:
      image: "postgres:12.2"
      restart: unless-stopped
      networks:
        - "gpsnet"
      env_file:
        - ".env"
      volumes:
        - ./db-data:/var/lib/postgresql/data
        - ./migrator/init:/docker-entrypoint-initdb.d/
      ports:
        - 5432:5432

    migrator:
      image: "migrate/migrate"
      restart: on-failure:10
      networks:
        - "gpsnet"
      volumes: 
        - ./migrator/migrations:/migrations
      env_file:
        - ".env"
      command: ["-path", "./migrations", "-database",  "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB?sslmode=disable", "up"]
      depends_on: 
        - "db"

  networks:
    gpsnet:
      driver: bridge
      