version: '3'

networks:
  gpsnet:
    driver: bridge


services:

  mongo:
    image: mongo:4.1
    networks:
      - gpsnet
  
  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - gpsnet
  
  graylog:
    image: graylog/graylog:3.2
    networks:
      - gpsnet
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
  
     
  db:
    image: postgres:12.2
    restart: always
    networks:
      - gpsnet
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./migrator/init:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  migrator:
    image: migrate/migrate
    networks:
      - gpsnet
    volumes: 
      - ./migrator/migrations:/migrations
    environment:
      - UM_PASSWORD
    env_file:
      - .env
    command: ["-path", "./migrations", "-database",  "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB?sslmode=disable", "up"]
    depends_on: 
      - db



  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - gpsnet
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"
  
  consul-agent-2:
    networks:
      - gpsnet
    build: ./config/consul_registr
    command: "-retry-join consul-server-bootstrap -client 0.0.0.0"
    depends_on:
    - consul-server-bootstrap

  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
  
#  usermanager:
#    container_name: usermanager
#    image: "github.com/lvl484/user-manager"
#    networks:
#      - gpsnet
#    ports:
#      - "8000:8000"
#      - "8001:8001"
#    env_file:
#      - ./userApp/.env
#    build:
#      dockerfile: Dockerfile
#      context: ./userApp
#    environment:
#      - SERVICE_NAME=usermanager
#      - BIND_IP=0.0.0.0
#      - BIND_PORT=8000
#      - BIND_DEBUG_PORT=8001
#      - CONSUL_ADDRESS=consul:8500
          
     
