  version: "3"

  services:
    db:
      image: "postgres:9.6.17"
      restart: unless-stopped
      networks:
        - "gpsnet"
      env_file:
        - ".env"
      volumes:
        - ./db-data:/var/lib/postgresql/data
        - ./init:/docker-entrypoint-initdb.d/
      ports:
        - 7777:5432

    migrator:
      image: "migrate/migrate"
      networks:
        - "gpsnet"
      volumes: 
        - ./migrations:/migrations
      environment:
          - UM_PASSWORD
      env_file:
        - ".env"
      command: ["-path", "./migrations", "-database",  "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB?sslmode=disable", "up"]
      depends_on: 
        - "db"

  networks:
    gpsnet:
      driver: bridge